version: "0"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      HOST: 0.0.0.0
      PORT: 3001

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      URL: http://backend:3001
    depends_on:
      - backend
